const recordActionTypes = {
  SET_RECORD: "SET_RECORD",
  DOWNLOAD_RECORD_START: "DOWNLOAD_RECORD_START",
  DOWNLOAD_RECORD_SUCCESS: "DOWNLOAD_RECORD_SUCCESS",
  DOWNLOAD_RECORD_FAILURE: "DOWNLOAD_RECORD_FAILURE",
  UPLOAD_RECORD_START: "UPLOAD_RECORD_START",
  UPLOAD_RECORD_SUCCESS: "UPLOAD_RECORD_SUCCESS",
  UPLOAD_RECORD_FAILURE: "UPLOAD_RECORD_FAILURE",
  CLEAR_RECORD: "CLEAR_RECORD",
};

export default recordActionTypes;
